export const USER_ACTIONS = {
    LOADED_CONTACTS: 'LOADED_CONTACTS',
    CLEAR_SESSION: 'CLEAR_SESSION',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
};

export const LOADING = {
    SET_LOADING: 'SET_LOADING',
    STOP_LOADING: 'STOP_LOADING',
    LOADING_PROFILE: 'LOADING_PROFILE',
    LOADED_PROFILE: 'LOADED_PROFILE',
};
export const PROFILE_ACTIONS = {
    LOADED: 'PROFILE_LOADED',
    UPDATED: 'PROFILE_UPDATED'
}


export const SET_ALERT = 'SET_ALERT'

export const NETWORK_ACTIONS = {
    UPDATE: 'UPDATE_NETWORK_STATUS',
}

